### ISSUE TITLE
输入搜索词后无法退格删除

### ISSUE THREAD

**Issue by ghost** [Yggdroot/Yoyo-leaf#2]
比如搜索 ab
打成了abc
我想把c删掉
发现程序卡住了，不给机会纠正，无法把abc退格成ab

**Comment by Yggdroot** [comment]
按退格键不行吗？

**Comment by ghost** [comment]
centos 7 刚刚编译好的，没反应，按del可以退格键没有反应

**Comment by Yggdroot** [comment]
明白了，这是键码设置的问题，BS我用的是127，你用的是什么终端？可以设置的。

**Comment by ghost** [comment]
mobaxterm连的，不过就运行这个有问题，我退出来其他的地方都没有问题

**Comment by Yggdroot** [comment]
mobaxterm默认BS好像是ctrl-H，应该有地方可以设置的。

**Comment by Yggdroot** [comment]
https://blog.csdn.net/tcliuwenwen/article/details/108221351

**Comment by ghost** [comment]
是这个原因，mobaxterm默认就勾选了发送^H，取消了这个选项可以用了
