### ISSUE TITLE
大佬，面对长行的时候会卡住

### ISSUE THREAD

**Issue by jqhr** [Yggdroot/Yoyo-leaf#3]
环境：
 deepin v20, 基于debian 10
复现步骤:
```sh
 rg '' | yy
```
查找文件内容的时候，如果碰到长行就卡住了，cpu飙到100%，比如js或者css之类的文件会把整个文件去换行符节省空间，因此文件只有一行。
怎么破？

**Comment by jqhr** [comment]
![录屏_deepin-terminal_20220408153511](https://user-images.githubusercontent.com/23305067/162388842-e0869d2b-4a9e-4cc6-b1e5-fd65f565d778.gif)

**Comment by Yggdroot** [comment]
能否传一个这样的文件我试试？

**Comment by jqhr** [comment]
[out.tar.gz](https://github.com/Yggdroot/Yoyo-leaf/files/8451203/out.tar.gz)
这是我把目录下最大的文件给整一压缩包，虽然只有两百多个文件，但还是会卡死。

**Comment by Yggdroot** [comment]
好的，谢谢，我看看。

**Comment by Yggdroot** [comment]
修复了，请再试一下。

**Comment by jqhr** [comment]
好的，我试试

**Comment by jqhr** [comment]
好的，非常感谢大佬
