### ISSUE TITLE
Windows下如何编译？

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/Yoyo-leaf#4]
没看见文档 简单试了下 编译不通过
![image](https://user-images.githubusercontent.com/6241431/179859458-e794bb3b-89fe-4e8a-a589-b1894b41fb4d.png)

**Comment by Yggdroot** [comment]
不支持Windows。

**Comment by gVimer** [comment]
MAC上是这样的 正常吗
![image](https://user-images.githubusercontent.com/6241431/179879008-c3e7897b-5377-4629-8f0d-54642fddf054.png)

**Comment by Yggdroot** [comment]
如果yy没有加入到PATH环境变量，只能：./yy

**Comment by gVimer** [comment]
多谢 可以了

**Comment by gVimer** [comment]
![image](https://user-images.githubusercontent.com/6241431/179880366-b42b5718-a166-4dd0-8277-17ebbcb2d631.png)
有个小问题 用PUTTY远程的时候这个乱码了

**Comment by Yggdroot** [comment]
可能需要设置一下字体字符集什么的。
